Nonrandom stub and existence checks
bendichter/to_nwb pull request #4
Opened 2020-08-29 20:16 UTC by CodyCBakerPhD

A couple of changes in this PR, mostly small.

1) Altered all of the currently used stubs to return a truncated amount of actual data rather than random noise.
2) Added more file existence checks prior to file access.
3) Added improved type checking to functions.
4) Enforced PEP8 throughout.
5) Enforced Numpy docstring format throughout.

6) Also found a trailing bs4 soup reference in the currently unused waveforms call; fixed to reference appropriate field of lxml root.

2020-08-29 20:20 UTC, CodyCBakerPhD commented
Still left to do in another couple PR's is...

A) Instead of defaulting certain parameters such as `fs` to hard-coded values, retrieve these from an `.XML` file.
B) Replace the use of `os.path` with `pathlib`.

C) Deal with functions like `read_spike_times` and `read_spike_clustering` with regards to our new usage of `SpikeInterface`, which contains all of this information. This could include extending some of the functions in this library that inter-rely on these calls to alternatively receiving a sorting extractor object assumed to contain the appropriate information.

How does that all sound?

2020-08-29 21:02 UTC, bendichter requested changes
looks good overall. A few requested changes.

2020-08-29 21:02 UTC, bendichter commented on to_nwb/neuroscope.py
> +def get_channel_groups(session_path: str, xml_filepath: Optional[str]):
```suggestion
def get_channel_groups(session_path: str, xml_filepath: Optional[str] = None):
```

2020-08-29 21:02 UTC, bendichter commented on to_nwb/neuroscope.py
> +def get_shank_channels(session_path: str, xml_filepath: Optional[str]):
```suggestion
def get_shank_channels(session_path: str, xml_filepath: Optional[str] = None):
```

2020-08-29 21:02 UTC, bendichter commented on to_nwb/neuroscope.py
> +def get_lfp_sampling_rate(session_path: str, xml_filepath: Optional[str]):
```suggestion
def get_lfp_sampling_rate(session_path: str, xml_filepath: Optional[str] = None):
```

2020-08-29 21:02 UTC, bendichter commented on to_nwb/neuroscope.py
> +        channel_groups = None
if there is no xml file, the function should fail

2020-08-29 21:02 UTC, bendichter commented on to_nwb/neuroscope.py
> +        shank_channels = None
if there is no xml file, the function should fail

2020-08-29 21:02 UTC, bendichter commented on to_nwb/neuroscope.py
> +        lfp_sampling_rate = None
if there is no xml file, the function should fail

2020-08-29 21:02 UTC, bendichter commented on to_nwb/neuroscope.py
> +    """Write the electrode table to the NWBFile object.
```suggestion
def write_electrode_table(nwbfile: NWBFile, session_path: str,
                          electrode_positions: Optional[ArrayLike] = None,
                          impedances: Optional[ArrayLike] = None,
                          locations: Optional[ArrayLike] = None,
                          filterings: Optional[ArrayLike] = None,
                          custom_columns: Optional[List[dict]] = None,
                          max_shanks: Optional[int] = None):
    """Write the electrode table to the NWBFile object.
```

2020-08-29 21:02 UTC, bendichter commented on to_nwb/neuroscope.py
> +    session_path: PathType
```suggestion
    session_path: str
```

2020-08-29 21:02 UTC, bendichter commented on to_nwb/neuroscope.py
> +                                            count=max_size*n_channels).reshape(-1, n_channels)
oh cool, I didn't know about the count arg. This is nicely done.

2020-08-29 21:02 UTC, bendichter commented on to_nwb/neuroscope.py
> +              electrode_inds: Optional[List[int]],
```suggestion
def write_lfp(nwbfile: NWBFile, data: ArrayLike, fs: float,
              electrode_inds: Optional[List[int]] = None,
```

2020-08-29 21:02 UTC, bendichter commented on to_nwb/neuroscope.py
> +def get_events(session_path: str, suffixes: Iterable[int]):
nice use of Iterable

2020-08-29 21:02 UTC, bendichter commented on to_nwb/neuroscope.py
> +              custom_cols: Optional[List[dict]],
```suggestion
              custom_cols: Optional[List[dict]] = None,
```

2020-08-29 21:15 UTC, CodyCBakerPhD commented on to_nwb/neuroscope.py
> +        channel_groups = None
So you would prefer if it were an `assert`?

2020-08-29 21:27 UTC, bendichter commented on to_nwb/neuroscope.py
> +        channel_groups = None
Yes, that sounds like a good idea!

2020-08-29 22:35 UTC, bendichter commented
@CodyCBakerPhD I don't really understand why you are editing this file. Is this necessary for advancing NWB Conversion Tools?

2020-08-31 16:50 UTC, CodyCBakerPhD commented
The changes to the stubbing methods are necessary for ensuring the `buzsaki-lab-to-nwb` converter is processing the original data correctly; this is how I detected those output differences for the LFP-related computations that are still being investigated.

The other changes are just small things to spruce it up; for the `buzsaki-lab-to-nwb`, we end up using this repository just as much as `SpikeInterface` (more, if raw data is missing), so I figured it should be maintained similarly. If you don't want any of the other proposed changes, however, just let me know and these stub changes are all we need for now.

Nothing about this directly effects `nwb-conversion-tools` unless we eventually decide to generalize some of the other DataInterface classes (such as LFPDataInterface) away from their current specific usage in `buzsaki-lab-to-nwb`.

2020-09-08 18:32 UTC, CodyCBakerPhD commented on to_nwb/neuroscope.py
> +    session_path: PathType
Fixed

2020-09-08 18:32 UTC, CodyCBakerPhD commented on to_nwb/neuroscope.py
> +def get_lfp_sampling_rate(session_path: str, xml_filepath: Optional[str]):
Fixed

2020-09-08 18:32 UTC, CodyCBakerPhD commented on to_nwb/neuroscope.py
> +def get_shank_channels(session_path: str, xml_filepath: Optional[str]):
Fixed

2020-09-08 18:32 UTC, CodyCBakerPhD commented on to_nwb/neuroscope.py
> +              custom_cols: Optional[List[dict]],
Fixed

2020-09-08 18:42 UTC, CodyCBakerPhD commented on to_nwb/neuroscope.py
> +        shank_channels = None
Fixed

2020-09-08 18:42 UTC, CodyCBakerPhD commented on to_nwb/neuroscope.py
> +        channel_groups = None
Fixed

2020-09-08 18:42 UTC, CodyCBakerPhD commented on to_nwb/neuroscope.py
> +def get_channel_groups(session_path: str, xml_filepath: Optional[str]):
Fixed

2020-09-08 18:43 UTC, CodyCBakerPhD commented
OK, all changes implemented. This particular update should be good to merge if you agree.

2020-09-08 19:02 UTC, merged